# change the followings to match your Github username and repo name
baseurl: "/Jinhao_page" # the name of your github repo
url: "https://hjinhao066.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Self-intro"
description: A personal homepage form jinhao 

# color theme for links
theme-color: yellow # indigo|yellow|pink|green|stone|

# homepage information
author: Jinhao Hu
author-bio: false # change to false to hide
author-image: jin.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog
- text: Skill
  permalink: skill
- text: Life
  permalink: life
# use false to turn off any social media links
twitter: https://twitter.com/hjinhao066
facebook: https://www.facebook.com/profile.php?id=61550737555349
instagram: https://www.instagram.com/alex_hu2930/
xiaohongshu: https://www.xiaohongshu.com/user/profile/61206a8c0000000001006be8
github: https://github.com/hjinhao066
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
